language: node_js
node_js:
  - "0.12"
  - "iojs-3"
  - "4"
  - "5"
script: '[[ "${TRAVIS_PULL_REQUEST}" != "false" && "${NPM_COMMAND}" == "test-in-browsers" ]] || npm run $NPM_COMMAND'
sudo: false
env:
  global:
    # SAUCE_USERNAME
    - secure: "fn/RYhGes0GsWstAOsaMo1iMYHvLiCcwwpWG2SEF4BA/kuiho9BzpQsKmw+DuQgK7fNyhOMCatoA5fgjBUXs+5xSfHkVVvFukPKEMPVRfRIbwxVfSfMPeQ08PYd9s82mdZHbtSVAXS3LylXTADHI7mtrRG4HWcyVLBskbSu1hdQ="
    # SAUCE_ACCESS_KEY
    - secure: "FYtt78twwWbGY7YWzAG0H4Tycso7Dcuq7mRVuplhxV9KRYOqLS+kcSCjIsGMkF8bWqaPu1hYRW/gvOwDGIEjH+aaCGO7BNlHNwhaBn5F7kfmpkQXzkdu78puBcjbKi1OZMeGZs5YCsGEv5pNKFQNzFQxuc464aa0KK1Q/6t4RmU="
  matrix:
    - NPM_COMMAND=test
    - NPM_COMMAND=test-with-coverage
    - NPM_COMMAND=test-in-browsers
matrix:
  exclude:
    # don't test in browsers more than once (already done with node 5)
    - node_js: "0.12"
      env: NPM_COMMAND=test-in-browsers
    - node_js: "iojs-3"
      env: NPM_COMMAND=test-in-browsers
    - node_js: "4"
      env: NPM_COMMAND=test-in-browsers
    # don't collect code coverage more than once (with node 5)
    - node_js: "0.12"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "iojs-3"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "4"
      env: NPM_COMMAND=test-with-coverage
    # already tested with coverage (with node 5). no need to test again without
    - node_js: "5"
      env: NPM_COMMAND=test
